export const GET_POSTS = "GET_POSTS";
export const ADD_NEWSLETTER = "ADD_NEWSLETTER";
export const CLEAR_NEWSLETTER = "CLEAR_NEWSLETTER";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const CLEAR_POST_BY_ID = "CLEAR_POST_BY_ID";
export const SEND_MESSAGE = "SEND_MESSAGE";
